### ISSUE TITLE
左移失敗

### ISSUE THREAD

**Issue by eddiewentw** [EddieWen-Taiwan/happy-vacation#2]
2017-02-02 無法左移至 2017-01-26

**Comment by EddieWen-Taiwan** [comment]
解決了哈哈
原本是因為 2017 新年假期沒加入六日( 01/28, 01/29 )的部分，所以連假有斷層，懶得處理了直接把六日也補成新年假期。

**Comment by EddieWen-Taiwan** [comment]
解決了哈哈
原本是因為 2017 新年假期沒加入六日( 01/28, 01/29 )的部分，所以連假有斷層，懶得處理了直接把六日也補成新年假期。

**Comment by eddiewentw** [comment]
解決了哈哈
原本是因為 2017 新年假期沒加入六日( 01/28, 01/29 )的部分，所以連假有斷層，懶得處理了直接把六日也補成新年假期。
